package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ConsumerEventDto implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("ID")
	private java.lang.String ID;
	@org.kie.api.definition.type.Label("AGGREGATE_ID")
	private java.lang.String AGGREGATE_ID;
	@org.kie.api.definition.type.Label("AGGREGATE_TYPE")
	private java.lang.String AGGREGATE_TYPE;
	@org.kie.api.definition.type.Label("CREATED_BY")
	private java.lang.String CREATED_BY;
	@org.kie.api.definition.type.Label("CREATED_ON")
	private java.lang.String CREATED_ON;
	@org.kie.api.definition.type.Label("EVENT_TYPE")
	private java.lang.String EVENT_TYPE;
	@org.kie.api.definition.type.Label("PAYLOAD")
	private java.lang.String PAYLOAD;

	@org.kie.api.definition.type.Label(value = "data")
	private java.lang.String data;

	public ConsumerEventDto() {
	}

	public java.lang.String getID() {
		return this.ID;
	}

	public void setID(java.lang.String ID) {
		this.ID = ID;
	}

	public java.lang.String getAGGREGATE_ID() {
		return this.AGGREGATE_ID;
	}

	public void setAGGREGATE_ID(java.lang.String AGGREGATE_ID) {
		this.AGGREGATE_ID = AGGREGATE_ID;
	}

	public java.lang.String getAGGREGATE_TYPE() {
		return this.AGGREGATE_TYPE;
	}

	public void setAGGREGATE_TYPE(java.lang.String AGGREGATE_TYPE) {
		this.AGGREGATE_TYPE = AGGREGATE_TYPE;
	}

	public java.lang.String getCREATED_BY() {
		return this.CREATED_BY;
	}

	public void setCREATED_BY(java.lang.String CREATED_BY) {
		this.CREATED_BY = CREATED_BY;
	}

	public java.lang.String getCREATED_ON() {
		return this.CREATED_ON;
	}

	public void setCREATED_ON(java.lang.String CREATED_ON) {
		this.CREATED_ON = CREATED_ON;
	}

	public java.lang.String getEVENT_TYPE() {
		return this.EVENT_TYPE;
	}

	public void setEVENT_TYPE(java.lang.String EVENT_TYPE) {
		this.EVENT_TYPE = EVENT_TYPE;
	}

	public java.lang.String getPAYLOAD() {
		return this.PAYLOAD;
	}

	public void setPAYLOAD(java.lang.String PAYLOAD) {
		this.PAYLOAD = PAYLOAD;
	}

	public java.lang.String getData() {
		return this.data;
	}

	public void setData(java.lang.String data) {
		this.data = data;
	}

	public ConsumerEventDto(java.lang.String ID, java.lang.String AGGREGATE_ID,
			java.lang.String AGGREGATE_TYPE, java.lang.String CREATED_BY,
			java.lang.String CREATED_ON, java.lang.String EVENT_TYPE,
			java.lang.String PAYLOAD, java.lang.String data) {
		this.ID = ID;
		this.AGGREGATE_ID = AGGREGATE_ID;
		this.AGGREGATE_TYPE = AGGREGATE_TYPE;
		this.CREATED_BY = CREATED_BY;
		this.CREATED_ON = CREATED_ON;
		this.EVENT_TYPE = EVENT_TYPE;
		this.PAYLOAD = PAYLOAD;
		this.data = data;
	}

}