package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderImportEventPayload implements java.io.Serializable {

    private RevenueCollectionDto revCollectionProcess;
    private String authToken;

    // Getters and Setters
    public RevenueCollectionDto getRevCollectionProcess() {
        return revCollectionProcess;
    }

    public void setRevCollectionProcess(RevenueCollectionDto revCollectionProcess) {
        this.revCollectionProcess = revCollectionProcess;
    }

    public String getAuthToken() {
        return authToken;
    }

    public void setAuthToken(String authToken) {
        this.authToken = authToken;
    }


}