package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderImportApiRequest implements java.io.Serializable {

    private String source;
    private String originalFile;
    private String callbackMethod;
    private String callbackEndPoint;
    private String callbackFileName;
    private String httpEndpoint;
    private String requestType;
    private String threadId;
    private String type;
    private String inputFileName;

    // Getters and Setters
    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getOriginalFile() {
        return originalFile;
    }

    public void setOriginalFile(String originalFile) {
        this.originalFile = originalFile;
    }

    public String getCallbackMethod() {
        return callbackMethod;
    }

    public void setCallbackMethod(String callbackMethod) {
        this.callbackMethod = callbackMethod;
    }

    public String getCallbackEndPoint() {
        return callbackEndPoint;
    }

    public void setCallbackEndPoint(String callbackEndPoint) {
        this.callbackEndPoint = callbackEndPoint;
    }

    public String getCallbackFileName() {
        return callbackFileName;
    }

    public void setCallbackFileName(String callbackFileName) {
        this.callbackFileName = callbackFileName;
    }

    public String getHttpEndpoint() {
        return httpEndpoint;
    }

    public void setHttpEndpoint(String httpEndpoint) {
        this.httpEndpoint = httpEndpoint;
    }

    public String getRequestType() {
        return requestType;
    }

    public void setRequestType(String requestType) {
        this.requestType = requestType;
    }

    public String getThreadId() {
        return threadId;
    }

    public void setThreadId(String threadId) {
        this.threadId = threadId;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getInputFileName() {
        return inputFileName;
    }

    public void setInputFileName(String inputFileName) {
        this.inputFileName = inputFileName;
    }
}