package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PublishedEvent implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("status")
	private java.lang.String status;
	@org.kie.api.definition.type.Label("stepDescription")
	private java.lang.String stepDescription;
	@org.kie.api.definition.type.Label("payload")
	private java.lang.String payload;

	@org.kie.api.definition.type.Label(value = "processInstanceId")
	private java.lang.String processInstanceId;

	public PublishedEvent() {
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getStepDescription() {
		return this.stepDescription;
	}

	public void setStepDescription(java.lang.String stepDescription) {
		this.stepDescription = stepDescription;
	}

	public java.lang.String getPayload() {
		return this.payload;
	}

	public void setPayload(java.lang.String payload) {
		this.payload = payload;
	}

	public java.lang.String getProcessInstanceId() {
		return this.processInstanceId;
	}

	public void setProcessInstanceId(java.lang.String processInstanceId) {
		this.processInstanceId = processInstanceId;
	}

	public PublishedEvent(java.lang.String status,
			java.lang.String stepDescription, java.lang.String payload,
			java.lang.String processInstanceId) {
		this.status = status;
		this.stepDescription = stepDescription;
		this.payload = payload;
		this.processInstanceId = processInstanceId;
	}

}