package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RevenueCollectionDto {

	@org.kie.api.definition.type.Label("includeDraftoders")
	private java.lang.String includeDraftoders;

	public String getOrgId() {
		return orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	public String getBillToCustomerId() {
		return billToCustomerId;
	}

	public RevenueCollectionDto() {
		super();
	}

	@Override
	public String toString() {
		return "RevenueCollectionDto [processId=" + processId
				+ ", processName=" + processName + ", legalEntityId="
				+ legalEntityId + ", orgId=" + orgId + ", billToCustomerId="
				+ billToCustomerId + ", revGenerateType=" + revGenerateType
				+ ", cutoverDate=" + cutoverDate + ", startDate=" + startDate
				+ ", endDate=" + endDate + ", orders=" + orders
				+ ", batchStatus=" + batchStatus + ", failedProgram="
				+ failedProgram + ", orderIds=" + orderIds
				+ ", parentRequestId=" + parentRequestId
				+ ", includeDraftOrders=" + includeDraftoders + ", reProcess="
				+ reProcess + ", callBackName=" + callBackName
				+ ", revCollectionStatus=" + revCollectionStatus
				+ ", batchInvokedBy=" + batchInvokedBy
				+ ", revenueContractKey=" + revenueContractKey
				+ ", impactFlag=" + impactFlag + ", sparkRequestID="
				+ sparkRequestID + ", reprocessFlag=" + reprocessFlag
				+ ", configCode=" + configCode + ", programCode=" + programCode
				+ ", processReqId=" + processReqId + ", parentManualReqId="
				+ parentManualReqId + ", programDescWrapper="
				+ programDescWrapper + ", wrapperRequestId=" + wrapperRequestId
				+ "]";
	}

	public RevenueCollectionDto(String processId, String processName,
			Long legalEntityId, String orgId, String billToCustomerId,
			String revGenerateType, String cutoverDate, String startDate,
			String endDate, String orders, String batchStatus,
			String failedProgram, String orderIds, String parentRequestId,
			String includeDraftoders, String reProcess, String callBackName,
			String revCollectionStatus, String batchInvokedBy,
			String revenueContractKey, String impactFlag,
			String sparkRequestID, String reprocessFlag, String configCode,
			String programCode, String processReqId, String parentManualReqId,
			String programDescWrapper, String wrapperRequestId) {
		super();
		this.processId = processId;
		this.processName = processName;
		this.legalEntityId = legalEntityId;
		this.orgId = orgId;
		this.billToCustomerId = billToCustomerId;
		this.revGenerateType = revGenerateType;
		this.cutoverDate = cutoverDate;
		this.startDate = startDate;
		this.endDate = endDate;
		this.orders = orders;
		this.batchStatus = batchStatus;
		this.failedProgram = failedProgram;
		this.orderIds = orderIds;
		this.parentRequestId = parentRequestId;
		this.includeDraftoders = includeDraftoders;
		this.reProcess = reProcess;
		this.callBackName = callBackName;
		this.revCollectionStatus = revCollectionStatus;
		this.batchInvokedBy = batchInvokedBy;
		this.revenueContractKey = revenueContractKey;
		this.impactFlag = impactFlag;
		this.sparkRequestID = sparkRequestID;
		this.reprocessFlag = reprocessFlag;
		this.configCode = configCode;
		this.programCode = programCode;
		this.processReqId = processReqId;
		this.parentManualReqId = parentManualReqId;
		this.programDescWrapper = programDescWrapper;
		this.wrapperRequestId = wrapperRequestId;
	}

	public void setBillToCustomerId(String billToCustomerId) {
		this.billToCustomerId = billToCustomerId;
	}

	public String getRevGenerateType() {
		return revGenerateType;
	}

	public void setRevGenerateType(String revGenerateType) {
		this.revGenerateType = revGenerateType;
	}

	public String getCutoverDate() {
		return cutoverDate;
	}

	public void setCutoverDate(String cutoverDate) {
		this.cutoverDate = cutoverDate;
	}

	public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public String getOrders() {
		return orders;
	}

	public void setOrders(String orders) {
		this.orders = orders;
	}

	public String getBatchStatus() {
		return batchStatus;
	}

	public void setBatchStatus(String batchStatus) {
		this.batchStatus = batchStatus;
	}

	public String getFailedProgram() {
		return failedProgram;
	}

	public void setFailedProgram(String failedProgram) {
		this.failedProgram = failedProgram;
	}

	public String getOrderIds() {
		return orderIds;
	}

	public void setOrderIds(String orderIds) {
		this.orderIds = orderIds;
	}

	public String getParentRequestId() {
		return parentRequestId;
	}

	public void setParentRequestId(String parentRequestId) {
		this.parentRequestId = parentRequestId;
	}

	public String getReProcess() {
		return reProcess;
	}

	public void setReProcess(String reProcess) {
		this.reProcess = reProcess;
	}

	public String getCallBackName() {
		return callBackName;
	}

	public void setCallBackName(String callBackName) {
		this.callBackName = callBackName;
	}

	public String getRevCollectionStatus() {
		return revCollectionStatus;
	}

	public void setRevCollectionStatus(String revCollectionStatus) {
		this.revCollectionStatus = revCollectionStatus;
	}

	public String getBatchInvokedBy() {
		return batchInvokedBy;
	}

	public void setBatchInvokedBy(String batchInvokedBy) {
		this.batchInvokedBy = batchInvokedBy;
	}

	public String getRevenueContractKey() {
		return revenueContractKey;
	}

	public void setRevenueContractKey(String revenueContractKey) {
		this.revenueContractKey = revenueContractKey;
	}

	public String getImpactFlag() {
		return impactFlag;
	}

	public void setImpactFlag(String impactFlag) {
		this.impactFlag = impactFlag;
	}

	public String getSparkRequestID() {
		return sparkRequestID;
	}

	public void setSparkRequestID(String sparkRequestID) {
		this.sparkRequestID = sparkRequestID;
	}

	public String getReprocessFlag() {
		return reprocessFlag;
	}

	public void setReprocessFlag(String reprocessFlag) {
		this.reprocessFlag = reprocessFlag;
	}

	public String getConfigCode() {
		return configCode;
	}

	public void setConfigCode(String configCode) {
		this.configCode = configCode;
	}

	public String getProgramCode() {
		return programCode;
	}

	public void setProgramCode(String programCode) {
		this.programCode = programCode;
	}

	public String getProcessReqId() {
		return processReqId;
	}

	public void setProcessReqId(String processReqId) {
		this.processReqId = processReqId;
	}

	public String getParentManualReqId() {
		return parentManualReqId;
	}

	public void setParentManualReqId(String parentManualReqId) {
		this.parentManualReqId = parentManualReqId;
	}

	public String getProgramDescWrapper() {
		return programDescWrapper;
	}

	public void setProgramDescWrapper(String programDescWrapper) {
		this.programDescWrapper = programDescWrapper;
	}

	public String getWrapperRequestId() {
		return wrapperRequestId;
	}

	public void setWrapperRequestId(String wrapperRequestId) {
		this.wrapperRequestId = wrapperRequestId;
	}

	private String processId;
	private String processName;
	@org.kie.api.definition.type.Label("legalEntityId")
	private Long legalEntityId;
	private String orgId;
	private String billToCustomerId;
	private String revGenerateType;
	private String cutoverDate;
	private String startDate;
	private String endDate;
	private String orders;
	private String batchStatus;
	private String failedProgram;
	private String orderIds;
	private String parentRequestId;
	private String reProcess;
	private String callBackName;
	private String revCollectionStatus;
	private String batchInvokedBy;
	private String revenueContractKey;
	private String impactFlag;
	private String sparkRequestID;
	private String reprocessFlag;
	private String configCode;
	private String programCode;
	private String processReqId;
	private String parentManualReqId;
	private String programDescWrapper;
	private String wrapperRequestId;

	// Getters and Setters
	public String getProcessId() {
		return processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	public String getProcessName() {
		return processName;
	}

	public void setProcessName(String processName) {
		this.processName = processName;
	}

	public java.lang.String getIncludeDraftoders() {
		return this.includeDraftoders;
	}

	public void setIncludeDraftoders(java.lang.String includeDraftoders) {
		this.includeDraftoders = includeDraftoders;
	}

	public java.lang.Long getLegalEntityId() {
		return this.legalEntityId;
	}

	public void setLegalEntityId(java.lang.Long legalEntityId) {
		this.legalEntityId = legalEntityId;
	}

	public RevenueCollectionDto(java.lang.String includeDraftoders,
			java.lang.String processId, java.lang.String processName,
			java.lang.Long legalEntityId, java.lang.String orgId,
			java.lang.String billToCustomerId,
			java.lang.String revGenerateType, java.lang.String cutoverDate,
			java.lang.String startDate, java.lang.String endDate,
			java.lang.String orders, java.lang.String batchStatus,
			java.lang.String failedProgram, java.lang.String orderIds,
			java.lang.String parentRequestId, java.lang.String reProcess,
			java.lang.String callBackName,
			java.lang.String revCollectionStatus,
			java.lang.String batchInvokedBy,
			java.lang.String revenueContractKey, java.lang.String impactFlag,
			java.lang.String sparkRequestID, java.lang.String reprocessFlag,
			java.lang.String configCode, java.lang.String programCode,
			java.lang.String processReqId, java.lang.String parentManualReqId,
			java.lang.String programDescWrapper,
			java.lang.String wrapperRequestId) {
		this.includeDraftoders = includeDraftoders;
		this.processId = processId;
		this.processName = processName;
		this.legalEntityId = legalEntityId;
		this.orgId = orgId;
		this.billToCustomerId = billToCustomerId;
		this.revGenerateType = revGenerateType;
		this.cutoverDate = cutoverDate;
		this.startDate = startDate;
		this.endDate = endDate;
		this.orders = orders;
		this.batchStatus = batchStatus;
		this.failedProgram = failedProgram;
		this.orderIds = orderIds;
		this.parentRequestId = parentRequestId;
		this.reProcess = reProcess;
		this.callBackName = callBackName;
		this.revCollectionStatus = revCollectionStatus;
		this.batchInvokedBy = batchInvokedBy;
		this.revenueContractKey = revenueContractKey;
		this.impactFlag = impactFlag;
		this.sparkRequestID = sparkRequestID;
		this.reprocessFlag = reprocessFlag;
		this.configCode = configCode;
		this.programCode = programCode;
		this.processReqId = processReqId;
		this.parentManualReqId = parentManualReqId;
		this.programDescWrapper = programDescWrapper;
		this.wrapperRequestId = wrapperRequestId;
	}

}
