package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RevenueCollectionApiRequest implements java.io.Serializable {

    private String processName;
    private String cutoverDate;
    private String startDate;
    private String endDate;
    private String revGenerateType;
    private String includeDraftOrders;
    private String billToCustomerId;
    private String legalEntityId;
    private String orderIds;
    private String customerBillTo;
    private String orders;
    private String reProcess;

    // Getters and Setters
    public String getProcessName() {
        return processName;
    }

    public void setProcessName(String processName) {
        this.processName = processName;
    }

    public String getCutoverDate() {
        return cutoverDate;
    }

    public void setCutoverDate(String cutoverDate) {
        this.cutoverDate = cutoverDate;
    }

    public String getStartDate() {
        return startDate;
    }

    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    public String getEndDate() {
        return endDate;
    }

    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    public String getRevGenerateType() {
        return revGenerateType;
    }

    public void setRevGenerateType(String revGenerateType) {
        this.revGenerateType = revGenerateType;
    }

    public String getIncludeDraftOrders() {
        return includeDraftOrders;
    }

    public void setIncludeDraftOrders(String includeDraftOrders) {
        this.includeDraftOrders = includeDraftOrders;
    }

    public String getBillToCustomerId() {
        return billToCustomerId;
    }

    public void setBillToCustomerId(String billToCustomerId) {
        this.billToCustomerId = billToCustomerId;
    }

    public String getLegalEntityId() {
        return legalEntityId;
    }

    public void setLegalEntityId(String legalEntityId) {
        this.legalEntityId = legalEntityId;
    }

    public String getOrderIds() {
        return orderIds;
    }

    public void setOrderIds(String orderIds) {
        this.orderIds = orderIds;
    }

    public String getCustomerBillTo() {
        return customerBillTo;
    }

    public void setCustomerBillTo(String customerBillTo) {
        this.customerBillTo = customerBillTo;
    }

    public String getOrders() {
        return orders;
    }

    public void setOrders(String orders) {
        this.orders = orders;
    }

    public String getReProcess() {
        return reProcess;
    }

    public void setReProcess(String reProcess) {
        this.reProcess = reProcess;
    }




}