package com.kafkaintegration;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OutboxEvent implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("payload")
	private java.lang.String payload;
	@org.kie.api.definition.type.Label(value = "orderImportStatus")
	private java.lang.String orderImportStatus;

	@org.kie.api.definition.type.Label(value = "revenueCollectionStatus")
	private java.lang.String revenueCollectionStatus;

	@org.kie.api.definition.type.Label(value = "watefallReportGenStatus")
	private java.lang.String watefallReportGenStatus;
	public OutboxEvent() {
	}

	public java.lang.String getPayload() {
		return this.payload;
	}

	public void setPayload(java.lang.String payload) {
		this.payload = payload;
	}

	@Override
	public String toString() {
		return "OutboxEvent [ payload = " + payload + " orderImportStatus = "
				+ orderImportStatus + " revenueCollectionStatus = "
				+ revenueCollectionStatus + " watefallReportGenStatus = "
				+ watefallReportGenStatus + " ] ";
	}

	public java.lang.String getOrderImportStatus() {
		return this.orderImportStatus;
	}

	public void setOrderImportStatus(java.lang.String orderImportStatus) {
		this.orderImportStatus = orderImportStatus;
	}

	public java.lang.String getRevenueCollectionStatus() {
		return this.revenueCollectionStatus;
	}

	public void setRevenueCollectionStatus(
			java.lang.String revenueCollectionStatus) {
		this.revenueCollectionStatus = revenueCollectionStatus;
	}

	public java.lang.String getWatefallReportGenStatus() {
		return this.watefallReportGenStatus;
	}

	public void setWatefallReportGenStatus(
			java.lang.String watefallReportGenStatus) {
		this.watefallReportGenStatus = watefallReportGenStatus;
	}

	public OutboxEvent(java.lang.String payload,
			java.lang.String orderImportStatus,
			java.lang.String revenueCollectionStatus,
			java.lang.String watefallReportGenStatus) {
		this.payload = payload;
		this.orderImportStatus = orderImportStatus;
		this.revenueCollectionStatus = revenueCollectionStatus;
		this.watefallReportGenStatus = watefallReportGenStatus;
	}
}